import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./provider";
import { ReduxProvider } from "./ReduxGlobals/provider";
import { NavbarSimple, StickyNavbar } from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <ThemeProvider>
        <html lang="en">
          <body className={inter.className}>
            <StickyNavbar />

            {children}
          </body>
        </html>
      </ThemeProvider>
    </ReduxProvider>
  );
}
